// Generated by https://quicktype.io

export interface CreditsResponse {
    cast: Cast[];
    crew: Cast[];
    id: number;
}

export interface Cast {
    adult: boolean;
    cast_id?: number;
    character?: string;
    credit_id: string;
    gender: number;
    id: number;
    known_for_department: Department;
    name: string;
    order?: number;
    original_name: string;
    popularity: number;
    profile_path: null | string;
    department?: Department;
    job?: string;
}

export enum Department {
    Acting = "Acting",
    Art = "Art",
    Directing = "Directing",
    Editing = "Editing",
    Production = "Production",
    Sound = "Sound",
    VisualEffects = "Visual Effects",
    Writing = "Writing",
}